[versions]
agp = "8.2.2"
coil-compose = "2.2.0"
droidlibs = "1.2.17"
firebase-bom = "33.0.0"
firebase-ui-auth = "7.2.0"
google-auth-library-oauth2-http = "1.23.0"
kotlin = "1.9.20"
core-ktx = "1.13.0"
junit = "4.13.2"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"
ktor-client-core = "2.3.11"
lifecycle-runtime-ktx = "2.7.0"
activity-compose = "1.9.0"
compose-bom = "2023.08.00"
google-service = "4.4.1"
navigation-compose = "2.7.7"
datastore-core = "1.0.0"
gson = "2.10.1"
koin-version = "3.5.3"
firebase-storage-ktx = "21.0.0"
generativeai = "0.9.0"
googleAndroidLibrariesMapsplatformSecretsGradlePlugin = "2.0.1"

[libraries]
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil-compose" }
droidlibs-compose-android = { module = "com.github.The-Streamliners.DroidLibs:compose-android", version.ref = "droidlibs" }
droidlibs-pickers = { module = "com.github.The-Streamliners.DroidLibs:pickers", version.ref = "droidlibs" }
droidlibs-base = { module = "com.github.The-Streamliners.DroidLibs:base", version.ref = "droidlibs" }
droidlibs-utils = { module = "com.github.The-Streamliners.DroidLibs:utils", version.ref = "droidlibs" }
droidlibs-helpers = { module = "com.github.The-Streamliners.DroidLibs:helpers", version.ref = "droidlibs" }
androidx-datastore-core = { module = "androidx.datastore: datastore-preferences-core", version.ref = "datastore-core"}
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-firestore = { module = "com.google.firebase:firebase-firestore" }
firebase-storage = { module = "com.google.firebase:firebase-storage" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
firebase-ui-auth = { module = "com.firebaseui:firebase-ui-auth", version.ref = "firebase-ui-auth" }
google-auth-library-oauth2-http = { module = "com.google.auth:google-auth-library-oauth2-http", version.ref = "google-auth-library-oauth2-http" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson"}
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose"}
koin-android = {module = "io.insert-koin:koin-androidx-compose", version.ref = "koin-version"}

junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor-client-core" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor-client-core" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
ui = { group = "androidx.compose.ui", name = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
material3 = { group = "androidx.compose.material3", name = "material3" }
material-icon-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
firebase-storage-ktx = { group = "com.google.firebase", name = "firebase-storage-ktx", version.ref = "firebase-storage-ktx" }
generativeai = { group = "com.google.ai.client.generativeai", name = "generativeai", version.ref = "generativeai" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
googleService = { id = "com.google.gms.google-services", version.ref = "google-service" }
google-android-libraries-mapsplatform-secrets-gradle-plugin = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "googleAndroidLibrariesMapsplatformSecretsGradlePlugin" }

